### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by EmpireWorld** [eslint/doctrine#194]
Hi.

I'm using Doctrine **2.0.0** version.

I'm using this **comment**:
```javascript
/**
 * Sample Comment
 *
 * @author Bayat
 */
```
I'm using the below **options**:
```javascript
let parsedComment = doctrine.parse(node.leadingComments.value, {
    unwrap: true,
    sloppy: true,
    lineNumber: true,
    recoverable: true
});
```

Here is the **output** of run:
```
/home/zahra/Desktop/OpenPress/opdoc/node_modules/doctrine/lib/doctrine.js:114
        doc = doc.replace(/^\/\*\*?/, '').replace(/\*\/$/, '');
                 ^

TypeError: Cannot read property 'replace' of undefined
    at unwrapComment (/home/zahra/Desktop/OpenPress/opdoc/node_modules/doctrine/lib/doctrine.js:114:18)
    at Object.parse (/home/zahra/Desktop/OpenPress/opdoc/node_modules/doctrine/lib/doctrine.js:835:26)
    at Controller.enter (/home/zahra/Desktop/OpenPress/opdoc/src/opdoc.js:74:54)
    at Controller.__execute (/home/zahra/Desktop/OpenPress/opdoc/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/home/zahra/Desktop/OpenPress/opdoc/node_modules/estraverse/estraverse.js:501:28)
    at Object.traverse (/home/zahra/Desktop/OpenPress/opdoc/node_modules/estraverse/estraverse.js:713:27)
    at fse.readFile (/home/zahra/Desktop/OpenPress/opdoc/src/opdoc.js:68:24)
    at /home/zahra/Desktop/OpenPress/opdoc/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:78:16
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
```

I want to get **parsed** comment object.

Thanks.

**Comment by EmpireWorld** [comment]
Thanks. i solved it.

It seems the espree removes the `/` from start and end of comment string.

So i wrapped it by `/` that solved. :smile:
